
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Nov 10 2021 09:47:59 WET (Nov 10 2021 09:47:59 UTC)

// Verification Directory fv/BATCHARGERctr 

module BATCHARGERctr(cc, tc, cv, imonen, vmonen, tmonen, vtok, vbat,
     ibat, tbat, vcutoff, vpreset, tempmin, tempmax, tmax, iend, clk,
     en, rstz, dvdd, dgnd);
  inout dgnd, dvdd;
  input vtok, clk, en, rstz;
  input [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  output cc, tc, cv, imonen, vmonen, tmonen;
  wire vtok, clk, en, rstz;
  wire [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  wire cc, tc, cv, imonen, vmonen, tmonen;
  wire [2:0] state;
  wire [7:0] time_cnt;
  wire [7:0] time_div;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       logic_1_1_net, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_35, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, timeout;
  assign imonen = cv;
  DBFRBEHD \state_reg[1] (.RB (n_178), .CKB (clk), .D (n_179), .Q
       (state[1]), .QB (UNCONNECTED));
  AN3EHD g6985__2398(.I1 (n_177), .I2 (n_165), .I3 (n_163), .O (n_179));
  DBFRBEHD \state_reg[0] (.RB (n_178), .CKB (clk), .D (n_176), .Q
       (state[0]), .QB (UNCONNECTED0));
  AOI112BHD g6987__5107(.A1 (n_173), .B1 (n_43), .C1 (n_57), .C2
       (n_155), .O (n_177));
  DBFRBEHD \state_reg[2] (.RB (n_178), .CKB (clk), .D (n_175), .Q
       (state[2]), .QB (UNCONNECTED1));
  AO222EHD g6988__6260(.A1 (n_157), .A2 (vtok), .B1 (n_171), .B2
       (n_174), .C1 (n_162), .C2 (n_169), .O (n_176));
  OAI22CHD g6993__4319(.A1 (n_158), .A2 (n_170), .B1 (n_172), .B2
       (n_174), .O (n_175));
  AOI22BHD g6992__8428(.A1 (n_172), .A2 (n_159), .B1 (n_156), .B2
       (n_174), .O (n_173));
  ND2CHD g6994__5526(.I1 (n_172), .I2 (n_168), .O (n_171));
  DBFRBEHD timeout_reg(.RB (n_148), .CKB (clk), .D (n_167), .Q
       (timeout), .QB (UNCONNECTED2));
  MAOI1CHD g7004__6783(.A1 (n_164), .A2 (n_169), .B1 (n_168), .B2
       (n_174), .O (n_170));
  OR2EHD g6995__3680(.I1 (state[0]), .I2 (n_166), .O (n_172));
  AO13EHD g6991__1617(.A1 (timeout), .B1 (n_160), .B2 (n_135), .B3
       (n_110), .O (n_167));
  OAI112BHD g6999__2802(.A1 (n_165), .B1 (n_169), .C1 (state[2]), .C2
       (n_98), .O (n_166));
  OAI12CHD g7032__1705(.A1 (n_163), .B1 (n_161), .B2 (n_154), .O
       (n_164));
  ND3CHD g6996__5122(.I1 (n_165), .I2 (n_161), .I3 (n_152), .O (n_162));
  AN3EHD g6997__8246(.I1 (n_144), .I2 (n_151), .I3 (n_100), .O (n_160));
  OAI12CHD g6998__7098(.A1 (n_153), .B1 (n_158), .B2 (n_67), .O
       (n_159));
  INVDHD g7000(.I (n_156), .O (n_157));
  OR2EHD g7001__6131(.I1 (n_174), .I2 (n_158), .O (n_155));
  INVCKDHD g7047(.I (n_174), .O (n_154));
  ND2CHD g7002__1881(.I1 (n_153), .I2 (n_158), .O (n_156));
  ND2DHD g7005__5115(.I1 (n_158), .I2 (state[2]), .O (n_165));
  OR2B1CHD g7038__7482(.I1 (n_152), .B1 (state[2]), .O (n_163));
  AN4B1BHD g7003__4733(.I1 (n_150), .I2 (n_138), .I3 (n_85), .B1
       (n_81), .O (n_151));
  MAO222EHD g7049__6161(.A1 (n_149), .B1 (vbat[7]), .C1 (n_49), .O
       (n_174));
  OAI112BHD g7014__9315(.A1 (n_141), .B1 (n_146), .C1 (n_139), .C2
       (tbat[7]), .O (n_158));
  ND2DHD g7046__9945(.I1 (state[0]), .I2 (n_147), .O (n_152));
  AOI112BHD g7015__2883(.A1 (n_142), .B1 (n_14), .C1 (time_cnt[0]), .C2
       (tmax[0]), .O (n_150));
  MAO222CHD g7058__2346(.A1 (n_143), .B1 (vbat[6]), .C1 (n_45), .O
       (n_149));
  DBFRBEHD \time_cnt_reg[7] (.RB (n_148), .CKB (clk), .D (n_145), .Q
       (time_cnt[7]), .QB (UNCONNECTED3));
  AOI112BHD g7048__1666(.A1 (timeout), .B1 (n_133), .C1 (n_134), .C2
       (iend[7]), .O (n_147));
  ND2CHD g7064__7410(.I1 (n_140), .I2 (tempmin[7]), .O (n_146));
  DBFRBEHD \time_cnt_reg[0] (.RB (n_148), .CKB (clk), .D (n_131), .Q
       (time_cnt[0]), .QB (UNCONNECTED4));
  MUX2CHD g7031__6417(.S (n_144), .A (time_cnt[7]), .B (n_119), .O
       (n_145));
  DBFRBEHD \time_cnt_reg[6] (.RB (n_148), .CKB (clk), .D (n_130), .Q
       (time_cnt[6]), .QB (UNCONNECTED5));
  MAO222CHD g7067__5477(.A1 (n_111), .B1 (vbat[5]), .C1 (n_46), .O
       (n_143));
  OAI22CHD g7043__2398(.A1 (tmax[7]), .A2 (n_137), .B1 (n_136), .B2
       (tmax[2]), .O (n_142));
  MAO222CHD g7044__5107(.A1 (n_113), .B1 (n_12), .C1 (tempmax[7]), .O
       (n_141));
  ND2CHD g7066__6260(.I1 (n_139), .I2 (tbat[7]), .O (n_140));
  AOI22BHD g7042__4319(.A1 (n_137), .A2 (tmax[7]), .B1 (n_136), .B2
       (tmax[2]), .O (n_138));
  DBFRBEHD \time_div_reg[5] (.RB (n_148), .CKB (clk), .D (n_122), .Q
       (time_div[5]), .QB (UNCONNECTED6));
  DBFRBEHD \time_div_reg[3] (.RB (n_148), .CKB (clk), .D (n_124), .Q
       (time_div[3]), .QB (UNCONNECTED7));
  DBFRBEHD \time_div_reg[1] (.RB (n_148), .CKB (clk), .D (n_126), .Q
       (time_div[1]), .QB (UNCONNECTED8));
  DBFRBEHD \time_cnt_reg[1] (.RB (n_148), .CKB (clk), .D (n_118), .Q
       (time_cnt[1]), .QB (UNCONNECTED9));
  DBFRBEHD \time_div_reg[6] (.RB (n_148), .CKB (clk), .D (n_127), .Q
       (time_div[6]), .QB (UNCONNECTED10));
  DBFRBEHD \time_div_reg[4] (.RB (n_148), .CKB (clk), .D (n_123), .Q
       (time_div[4]), .QB (UNCONNECTED11));
  DBFRBEHD \time_div_reg[7] (.RB (n_148), .CKB (clk), .D (n_116), .Q
       (time_div[7]), .QB (UNCONNECTED12));
  DBFRBEHD \time_div_reg[2] (.RB (n_148), .CKB (clk), .D (n_121), .Q
       (time_div[2]), .QB (UNCONNECTED13));
  DBFRBEHD \time_cnt_reg[5] (.RB (n_148), .CKB (clk), .D (n_115), .Q
       (time_cnt[5]), .QB (UNCONNECTED14));
  DBFRBEHD \time_cnt_reg[4] (.RB (n_148), .CKB (clk), .D (n_114), .Q
       (time_cnt[4]), .QB (UNCONNECTED15));
  DBFRBEHD \time_cnt_reg[3] (.RB (n_148), .CKB (clk), .D (n_120), .Q
       (time_cnt[3]), .QB (UNCONNECTED16));
  DBFRBEHD \time_div_reg[0] (.RB (n_148), .CKB (clk), .D (n_125), .Q
       (time_div[0]), .QB (UNCONNECTED17));
  DBFRBEHD \time_cnt_reg[2] (.RB (n_148), .CKB (clk), .D (n_117), .Q
       (time_cnt[2]), .QB (UNCONNECTED18));
  XOR2EHD g7051__8428(.I1 (tmax[6]), .I2 (n_128), .O (n_135));
  ND2CHD g7056__5526(.I1 (n_132), .I2 (ibat[7]), .O (n_134));
  NR2BHD g7057__6783(.I1 (ibat[7]), .I2 (n_132), .O (n_133));
  OAI22CHD g7024__3680(.A1 (time_cnt[0]), .A2 (n_129), .B1 (n_144), .B2
       (n_5), .O (n_131));
  MOAI1CHD g7030__1617(.A1 (n_129), .A2 (n_128), .B1 (n_129), .B2
       (time_cnt[6]), .O (n_130));
  OA112EHD g7040__2802(.A1 (logic_1_1_net), .B1 (n_101), .C1 (n_96),
       .C2 (time_div[6]), .O (n_127));
  OA112EHD g7034__1705(.A1 (logic_1_1_net), .B1 (n_23), .C1
       (time_div[1]), .C2 (time_div[0]), .O (n_126));
  OA112EHD g7036__5122(.A1 (logic_1_1_net), .B1 (n_69), .C1 (n_64), .C2
       (time_div[3]), .O (n_124));
  OA112EHD g7037__8246(.A1 (logic_1_1_net), .B1 (n_95), .C1 (n_72), .C2
       (time_div[4]), .O (n_123));
  OA112EHD g7033__7098(.A1 (logic_1_1_net), .B1 (n_52), .C1 (n_40), .C2
       (time_div[2]), .O (n_121));
  MOAI1CHD g7027__6131(.A1 (n_129), .A2 (n_84), .B1 (n_129), .B2
       (time_cnt[3]), .O (n_120));
  INVDHD g7050(.I (n_137), .O (n_119));
  MOAI1CHD g7025__1881(.A1 (n_129), .A2 (n_83), .B1 (n_129), .B2
       (time_cnt[1]), .O (n_118));
  MOAI1CHD g7026__5115(.A1 (n_129), .A2 (n_136), .B1 (n_129), .B2
       (time_cnt[2]), .O (n_117));
  OA112EHD g7041__7482(.A1 (n_129), .B1 (n_129), .C1 (n_108), .C2
       (time_div[7]), .O (n_116));
  MOAI1CHD g7029__4733(.A1 (n_129), .A2 (n_109), .B1 (n_129), .B2
       (time_cnt[5]), .O (n_115));
  MOAI1CHD g7028__6161(.A1 (n_129), .A2 (n_99), .B1 (n_129), .B2
       (time_cnt[4]), .O (n_114));
  MAO222CHD g7071__9315(.A1 (n_107), .B1 (n_7), .C1 (tbat[6]), .O
       (n_139));
  MAO222CHD g7054__9945(.A1 (n_104), .B1 (n_1), .C1 (tempmax[6]), .O
       (n_113));
  MAOI1CHD g7052__2883(.A1 (n_112), .A2 (time_cnt[7]), .B1
       (time_cnt[7]), .B2 (n_112), .O (n_137));
  MAO222CHD g7077__2346(.A1 (n_106), .B1 (vbat[4]), .C1 (n_44), .O
       (n_111));
  MAO222CHD g7061__1666(.A1 (n_102), .B1 (ibat[6]), .C1 (n_6), .O
       (n_132));
  INVDHD g7045(.I (n_129), .O (n_144));
  XOR2EHD g7060__7410(.I1 (tmax[5]), .I2 (n_109), .O (n_110));
  OAI12CHD g7059__6417(.A1 (n_112), .B1 (n_105), .B2 (time_cnt[6]), .O
       (n_128));
  ND2CHD g7053__5477(.I1 (n_108), .I2 (time_div[7]), .O (n_129));
  OAI22CHD g7078__2398(.A1 (tempmin[5]), .A2 (n_94), .B1 (n_93), .B2
       (n_103), .O (n_107));
  MAO222CHD g7088__5107(.A1 (n_89), .B1 (vbat[3]), .C1 (n_56), .O
       (n_106));
  ND2CHD g7063__6260(.I1 (n_105), .I2 (time_cnt[6]), .O (n_112));
  MAO222CHD g7065__4319(.A1 (n_88), .B1 (n_103), .C1 (tempmax[5]), .O
       (n_104));
  MAO222CHD g7072__8428(.A1 (n_87), .B1 (n_3), .C1 (ibat[5]), .O
       (n_102));
  INVDHD g7055(.I (n_101), .O (n_108));
  OAI12CHD g7069__5526(.A1 (n_92), .B1 (n_86), .B2 (time_cnt[5]), .O
       (n_109));
  MAOI1CHD g7070__6783(.A1 (n_99), .A2 (tmax[4]), .B1 (tmax[4]), .B2
       (n_99), .O (n_100));
  OA13CHD g7087__3680(.A1 (n_91), .B1 (n_90), .B2 (n_75), .B3
       (vpreset[4]), .O (n_98));
  AO12EHD g7068__1617(.A1 (n_96), .B1 (n_95), .B2 (n_80), .O (n_97));
  ND2DHD g7062__2802(.I1 (n_96), .I2 (time_div[6]), .O (n_101));
  AN2CHD g7084__1705(.I1 (n_93), .I2 (n_103), .O (n_94));
  INVDHD g7074(.I (n_92), .O (n_105));
  OA222CHD g7092__5122(.A1 (n_51), .A2 (n_62), .B1 (n_76), .B2 (n_90),
       .C1 (vpreset[7]), .C2 (n_22), .O (n_91));
  MAO222CHD g7095__8246(.A1 (n_74), .B1 (vbat[2]), .C1 (n_58), .O
       (n_89));
  MAO222CHD g7075__7098(.A1 (n_78), .B1 (n_82), .C1 (tempmax[4]), .O
       (n_88));
  MAO222CHD g7082__6131(.A1 (n_77), .B1 (n_11), .C1 (ibat[4]), .O
       (n_87));
  ND2CHD g7076__1881(.I1 (n_86), .I2 (time_cnt[5]), .O (n_92));
  AOI22BHD g7081__5115(.A1 (n_84), .A2 (tmax[3]), .B1 (n_83), .B2
       (tmax[1]), .O (n_85));
  MAO222CHD g7093__7482(.A1 (n_71), .B1 (n_82), .C1 (tempmin[4]), .O
       (n_93));
  OAI22CHD g7079__4733(.A1 (tmax[3]), .A2 (n_84), .B1 (n_83), .B2
       (tmax[1]), .O (n_81));
  NR2CHD g7073__6161(.I1 (n_80), .I2 (n_95), .O (n_96));
  OAI12CHD g7080__9315(.A1 (n_79), .B1 (n_73), .B2 (time_cnt[4]), .O
       (n_99));
  INVDHD g7083(.I (n_79), .O (n_86));
  MAO222CHD g7089__9945(.A1 (n_66), .B1 (n_70), .C1 (tempmax[3]), .O
       (n_78));
  MAO222CHD g7091__2883(.A1 (n_63), .B1 (n_4), .C1 (ibat[3]), .O
       (n_77));
  AO222CHD g7100__2346(.A1 (n_75), .A2 (vpreset[4]), .B1 (n_59), .B2
       (n_30), .C1 (n_28), .C2 (vpreset[3]), .O (n_76));
  MAO222EHD g7103__1666(.A1 (n_61), .B1 (vbat[1]), .C1 (n_48), .O
       (n_74));
  ND2CHD g7085__7410(.I1 (n_73), .I2 (time_cnt[4]), .O (n_79));
  ND2DHD g7086__6417(.I1 (n_72), .I2 (time_div[4]), .O (n_95));
  OAI12CHD g7094__5477(.A1 (n_68), .B1 (n_65), .B2 (time_cnt[3]), .O
       (n_84));
  OA112CHD g7099__2398(.A1 (n_60), .B1 (n_54), .C1 (n_70), .C2
       (tempmin[3]), .O (n_71));
  INVDHD g7090(.I (n_69), .O (n_72));
  INVDHD g7096(.I (n_68), .O (n_73));
  ND3CHD g7104__5107(.I1 (n_153), .I2 (n_67), .I3 (vtok), .O (n_168));
  MAO222CHD g7101__6260(.A1 (n_39), .B1 (n_26), .C1 (tempmax[2]), .O
       (n_66));
  ND2CHD g7098__4319(.I1 (n_65), .I2 (time_cnt[3]), .O (n_68));
  ND2DHD g7097__8428(.I1 (n_64), .I2 (time_div[3]), .O (n_69));
  MAO222CHD g7105__5526(.A1 (n_42), .B1 (n_13), .C1 (ibat[2]), .O
       (n_63));
  AOI22BHD g7110__6783(.A1 (n_38), .A2 (vbat[5]), .B1 (n_19), .B2
       (vbat[6]), .O (n_62));
  OR2EHD g7109__3680(.I1 (vbat[0]), .I2 (n_47), .O (n_61));
  OAI112BHD g7106__1617(.A1 (n_27), .B1 (n_53), .C1 (n_32), .C2
       (tbat[0]), .O (n_60));
  OAI222BHD g7114__2802(.A1 (vbat[1]), .A2 (n_9), .B1 (n_35), .B2
       (vbat[0]), .C1 (vbat[2]), .C2 (n_29), .O (n_59));
  OAI12CHD g7107__1705(.A1 (n_50), .B1 (n_41), .B2 (time_cnt[2]), .O
       (n_136));
  OAI22CHD g7121__5122(.A1 (vpreset[2]), .A2 (n_55), .B1 (n_57), .B2
       (vcutoff[2]), .O (n_58));
  OAI22CHD g7120__8246(.A1 (vpreset[3]), .A2 (n_55), .B1 (n_57), .B2
       (vcutoff[3]), .O (n_56));
  OR3B2CHD g7118__7098(.I1 (tempmin[2]), .B1 (n_53), .B2 (tbat[2]), .O
       (n_54));
  INVDHD g7102(.I (n_52), .O (n_64));
  OAI112BHD g7116__6131(.A1 (vbat[6]), .B1 (vbat[7]), .C1 (n_21), .C2
       (vbat[5]), .O (n_67));
  AO112EHD g7119__1881(.A1 (n_51), .B1 (n_37), .C1 (n_0), .C2
       (vpreset[5]), .O (n_90));
  INVDHD g7108(.I (n_50), .O (n_65));
  OAI22CHD g7126__5115(.A1 (vpreset[7]), .A2 (n_55), .B1 (n_57), .B2
       (vcutoff[7]), .O (n_49));
  OAI22CHD g7129__7482(.A1 (vpreset[1]), .A2 (n_55), .B1 (n_57), .B2
       (vcutoff[1]), .O (n_48));
  OAI22CHD g7124__4733(.A1 (vpreset[0]), .A2 (n_55), .B1 (n_57), .B2
       (vcutoff[0]), .O (n_47));
  OAI22CHD g7125__6161(.A1 (vpreset[5]), .A2 (n_55), .B1 (n_57), .B2
       (vcutoff[5]), .O (n_46));
  AOI22BHD g7128__9315(.A1 (n_57), .A2 (vpreset[6]), .B1 (n_55), .B2
       (vcutoff[6]), .O (n_45));
  AOI22BHD g7127__9945(.A1 (n_57), .A2 (vpreset[4]), .B1 (n_55), .B2
       (vcutoff[4]), .O (n_44));
  NR2CHD g7122__2883(.I1 (n_43), .I2 (n_153), .O (n_169));
  AN2CHD g7123__2346(.I1 (cv), .I2 (n_178), .O (n_148));
  MAO222CHD g7113__1666(.A1 (n_15), .B1 (n_8), .C1 (ibat[1]), .O
       (n_42));
  ND2CHD g7112__7410(.I1 (n_41), .I2 (time_cnt[2]), .O (n_50));
  ND2DHD g7111__6417(.I1 (n_40), .I2 (time_div[2]), .O (n_52));
  MAO222CHD g7115__5477(.A1 (n_16), .B1 (n_31), .C1 (tempmax[1]), .O
       (n_39));
  NR2BHD g7130__2398(.I1 (vpreset[5]), .I2 (n_37), .O (n_38));
  ND2CHD g7134__5107(.I1 (n_161), .I2 (state[1]), .O (tmonen));
  OAI12CHD g7131__6260(.A1 (vpreset[0]), .B1 (n_10), .B2 (vpreset[1]),
       .O (n_35));
  NR2BHD g7133__4319(.I1 (state[2]), .I2 (n_55), .O (cc));
  OR2B1CHD g7137__8428(.I1 (n_24), .B1 (state[2]), .O (vmonen));
  OAI12CHD g7136__5526(.A1 (tempmin[0]), .B1 (n_31), .B2 (tempmin[1]),
       .O (n_32));
  ND2CHD g7135__6783(.I1 (n_17), .I2 (vtok), .O (n_43));
  MAOI1CHD g7139__3680(.A1 (n_29), .A2 (vbat[2]), .B1 (vpreset[3]), .B2
       (n_28), .O (n_30));
  AOI22BHD g7138__1617(.A1 (n_31), .A2 (tempmin[1]), .B1 (n_26), .B2
       (tempmin[2]), .O (n_27));
  AN2CHD g7132__2802(.I1 (n_24), .I2 (state[2]), .O (tc));
  OAI12CHD g7141__1705(.A1 (n_20), .B1 (time_cnt[1]), .B2
       (time_cnt[0]), .O (n_83));
  NR3BHD g7140__5122(.I1 (state[1]), .I2 (n_2), .I3 (n_18), .O (cv));
  ND2CHD g7146__8246(.I1 (n_70), .I2 (tempmin[3]), .O (n_53));
  INVDHD g7117(.I (n_23), .O (n_40));
  AN2CHD g7143__7098(.I1 (n_22), .I2 (vpreset[7]), .O (n_51));
  INVDHD g7150(.I (n_55), .O (n_57));
  NR2BHD g7153__6131(.I1 (n_75), .I2 (n_28), .O (n_21));
  INVDHD g7149(.I (n_20), .O (n_41));
  NR2BHD g7147__1881(.I1 (vbat[6]), .I2 (n_19), .O (n_37));
  ND2DHD g7148__5115(.I1 (n_18), .I2 (state[0]), .O (n_161));
  ND2DHD g7151__7482(.I1 (state[2]), .I2 (state[1]), .O (n_17));
  OR2B1CHD g7145__4733(.I1 (tempmax[0]), .B1 (tbat[0]), .O (n_16));
  OR2B1CHD g7144__6161(.I1 (ibat[0]), .B1 (iend[0]), .O (n_15));
  AN2CHD g7157__9315(.I1 (en), .I2 (rstz), .O (n_178));
  ND2DHD g7158__9945(.I1 (state[1]), .I2 (state[0]), .O (n_55));
  NR2BHD g7152__2883(.I1 (tmax[0]), .I2 (time_cnt[0]), .O (n_14));
  NR2BHD g7142__2346(.I1 (state[1]), .I2 (state[0]), .O (n_24));
  ND2CHD g7154__1666(.I1 (time_cnt[1]), .I2 (time_cnt[0]), .O (n_20));
  ND2DHD g7155__7410(.I1 (time_div[1]), .I2 (time_div[0]), .O (n_23));
  NR2CHD g7156__6417(.I1 (state[1]), .I2 (state[2]), .O (n_153));
  INVCKDHD g7163(.I (iend[2]), .O (n_13));
  INVCKDHD g7180(.I (tbat[7]), .O (n_12));
  INVCKDHD g7164(.I (iend[4]), .O (n_11));
  INVCKDHD g7182(.I (vbat[1]), .O (n_10));
  INVCKDHD g7178(.I (vpreset[1]), .O (n_9));
  INVCKDHD g7159(.I (iend[1]), .O (n_8));
  INVCKDHD g7176(.I (tempmin[6]), .O (n_7));
  INVCKDHD g7179(.I (vpreset[6]), .O (n_19));
  INVDHD g7174(.I (state[2]), .O (n_18));
  INVCKDHD g7181(.I (tbat[4]), .O (n_82));
  INVCKDHD g7170(.I (vbat[7]), .O (n_22));
  INVCKDHD g7166(.I (tbat[3]), .O (n_70));
  INVCKDHD g7171(.I (vbat[3]), .O (n_28));
  INVCKDHD g7160(.I (iend[6]), .O (n_6));
  INVDHD g7173(.I (time_cnt[0]), .O (n_5));
  INVCKDHD g7162(.I (iend[3]), .O (n_4));
  INVCKDHD g7161(.I (iend[5]), .O (n_3));
  INVCKDHD g7184(.I (state[0]), .O (n_2));
  INVCKDHD g7167(.I (tbat[6]), .O (n_1));
  INVCKDHD g7183(.I (vbat[5]), .O (n_0));
  INVCKDHD g7175(.I (time_div[5]), .O (n_80));
  INVCKDHD g7177(.I (vpreset[2]), .O (n_29));
  INVCKDHD g7165(.I (tbat[2]), .O (n_26));
  INVCKDHD g7168(.I (tbat[5]), .O (n_103));
  INVCKDHD g7169(.I (tbat[1]), .O (n_31));
  INVCKDHD g7172(.I (vbat[4]), .O (n_75));
  INVCKDHD g7205(.I (time_div[0]), .O (n_125));
  INVCKDHD g7206(.I (n_97), .O (n_122));
  TIE1DHD tie_1_cell(.O (logic_1_1_net));
endmodule

