/*
###############################################################
#  Generated by:      Cadence Innovus 20.11-s130_1
#  OS:                Linux x86_64(Host ID fatima.novalocal)
#  Generated on:      Sun Jan  8 15:21:40 2023
#  Design:            BATCHARGERctr
#  Command:           saveNetlist BATCHARGERctr_pr.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Nov 10 2021 09:47:59 WET (Nov 10 2021 09:47:59 UTC)
// Verification Directory fv/BATCHARGERctr 
module BATCHARGERctr (
	cc, 
	tc, 
	cv, 
	imonen, 
	vmonen, 
	tmonen, 
	vtok, 
	vbat, 
	ibat, 
	tbat, 
	vcutoff, 
	vpreset, 
	tempmin, 
	tempmax, 
	tmax, 
	iend, 
	clk, 
	en, 
	rstz, 
	dvdd, 
	dgnd);
   output cc;
   output tc;
   output cv;
   output imonen;
   output vmonen;
   output tmonen;
   input vtok;
   input [7:0] vbat;
   input [7:0] ibat;
   input [7:0] tbat;
   input [7:0] vcutoff;
   input [7:0] vpreset;
   input [7:0] tempmin;
   input [7:0] tempmax;
   input [7:0] tmax;
   input [7:0] iend;
   input clk;
   input en;
   input rstz;
   inout dvdd;
   inout dgnd;

   // Internal wires
   wire FE_OFN14_tmonen;
   wire FE_OFN13_vmonen;
   wire FE_OFN11_cv;
   wire FE_OFN10_cc;
   wire [2:0] state;
   wire [7:0] time_cnt;
   wire [7:0] time_div;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire logic_1_1_net;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_35;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire timeout;

   BUFIHD FE_OFC14_tmonen (.O(tmonen),
	.I(FE_OFN14_tmonen));
   BUFIHD FE_OFC13_vmonen (.O(vmonen),
	.I(FE_OFN13_vmonen));
   BUFJHD FE_OFC12_cv (.O(imonen),
	.I(cv));
   BUFIHD FE_OFC11_cv (.O(cv),
	.I(FE_OFN11_cv));
   BUFIHD FE_OFC10_cc (.O(cc),
	.I(FE_OFN10_cc));
   OA12EHD FE_RC_2_0 (.O(n_116),
	.A1(n_129),
	.B1(n_108),
	.B2(time_div[7]));
   DBFRBEHD \state_reg[1]  (.Q(state[1]),
	.QB(UNCONNECTED),
	.D(n_179),
	.CKB(clk),
	.RB(n_178));
   AN3EHD g6985__2398 (.O(n_179),
	.I1(n_177),
	.I2(n_165),
	.I3(n_163));
   DBFRBEHD \state_reg[0]  (.Q(state[0]),
	.QB(UNCONNECTED0),
	.D(n_176),
	.CKB(clk),
	.RB(n_178));
   AOI112BHD g6987__5107 (.O(n_177),
	.A1(n_173),
	.B1(n_43),
	.C1(n_57),
	.C2(n_155));
   DBFRBEHD \state_reg[2]  (.Q(state[2]),
	.QB(UNCONNECTED1),
	.D(n_175),
	.CKB(clk),
	.RB(n_178));
   AO222EHD g6988__6260 (.O(n_176),
	.A1(n_157),
	.A2(vtok),
	.B1(n_171),
	.B2(n_174),
	.C1(n_162),
	.C2(n_169));
   OAI22CHD g6993__4319 (.O(n_175),
	.A1(n_158),
	.A2(n_170),
	.B1(n_172),
	.B2(n_174));
   AOI22BHD g6992__8428 (.O(n_173),
	.A1(n_172),
	.A2(n_159),
	.B1(n_156),
	.B2(n_174));
   ND2CHD g6994__5526 (.O(n_171),
	.I1(n_172),
	.I2(n_168));
   DBFRBEHD timeout_reg (.Q(timeout),
	.QB(UNCONNECTED2),
	.D(n_167),
	.CKB(clk),
	.RB(n_148));
   MAOI1CHD g7004__6783 (.O(n_170),
	.A1(n_164),
	.A2(n_169),
	.B1(n_168),
	.B2(n_174));
   OR2EHD g6995__3680 (.O(n_172),
	.I1(state[0]),
	.I2(n_166));
   AO13EHD g6991__1617 (.O(n_167),
	.A1(timeout),
	.B1(n_160),
	.B2(n_135),
	.B3(n_110));
   OAI112BHD g6999__2802 (.O(n_166),
	.A1(n_165),
	.B1(n_169),
	.C1(state[2]),
	.C2(n_98));
   OAI12CHD g7032__1705 (.O(n_164),
	.A1(n_163),
	.B1(n_161),
	.B2(n_154));
   ND3CHD g6996__5122 (.O(n_162),
	.I1(n_165),
	.I2(n_161),
	.I3(n_152));
   AN3EHD g6997__8246 (.O(n_160),
	.I1(n_144),
	.I2(n_151),
	.I3(n_100));
   OAI12CHD g6998__7098 (.O(n_159),
	.A1(n_153),
	.B1(n_158),
	.B2(n_67));
   INVDHD g7000 (.O(n_157),
	.I(n_156));
   OR2EHD g7001__6131 (.O(n_155),
	.I1(n_174),
	.I2(n_158));
   INVCKDHD g7047 (.O(n_154),
	.I(n_174));
   ND2CHD g7002__1881 (.O(n_156),
	.I1(n_153),
	.I2(n_158));
   ND2DHD g7005__5115 (.O(n_165),
	.I1(n_158),
	.I2(state[2]));
   OR2B1CHD g7038__7482 (.O(n_163),
	.I1(n_152),
	.B1(state[2]));
   AN4B1BHD g7003__4733 (.O(n_151),
	.I1(n_150),
	.I2(n_138),
	.I3(n_85),
	.B1(n_81));
   MAO222EHD g7049__6161 (.O(n_174),
	.A1(n_149),
	.B1(vbat[7]),
	.C1(n_49));
   OAI112BHD g7014__9315 (.O(n_158),
	.A1(n_141),
	.B1(n_146),
	.C1(n_139),
	.C2(tbat[7]));
   ND2DHD g7046__9945 (.O(n_152),
	.I1(state[0]),
	.I2(n_147));
   AOI112BHD g7015__2883 (.O(n_150),
	.A1(n_142),
	.B1(n_14),
	.C1(time_cnt[0]),
	.C2(tmax[0]));
   MAO222CHD g7058__2346 (.O(n_149),
	.A1(n_143),
	.B1(vbat[6]),
	.C1(n_45));
   DBFRBEHD \time_cnt_reg[7]  (.Q(time_cnt[7]),
	.QB(UNCONNECTED3),
	.D(n_145),
	.CKB(clk),
	.RB(n_148));
   AOI112BHD g7048__1666 (.O(n_147),
	.A1(timeout),
	.B1(n_133),
	.C1(n_134),
	.C2(iend[7]));
   ND2CHD g7064__7410 (.O(n_146),
	.I1(n_140),
	.I2(tempmin[7]));
   DBFRBEHD \time_cnt_reg[0]  (.Q(time_cnt[0]),
	.QB(UNCONNECTED4),
	.D(n_131),
	.CKB(clk),
	.RB(n_148));
   MUX2CHD g7031__6417 (.O(n_145),
	.S(n_144),
	.A(time_cnt[7]),
	.B(n_119));
   DBFRBEHD \time_cnt_reg[6]  (.Q(time_cnt[6]),
	.QB(UNCONNECTED5),
	.D(n_130),
	.CKB(clk),
	.RB(n_148));
   MAO222CHD g7067__5477 (.O(n_143),
	.A1(n_111),
	.B1(vbat[5]),
	.C1(n_46));
   OAI22CHD g7043__2398 (.O(n_142),
	.A1(tmax[7]),
	.A2(n_137),
	.B1(n_136),
	.B2(tmax[2]));
   MAO222CHD g7044__5107 (.O(n_141),
	.A1(n_113),
	.B1(n_12),
	.C1(tempmax[7]));
   ND2CHD g7066__6260 (.O(n_140),
	.I1(n_139),
	.I2(tbat[7]));
   AOI22BHD g7042__4319 (.O(n_138),
	.A1(n_137),
	.A2(tmax[7]),
	.B1(n_136),
	.B2(tmax[2]));
   DBFRBEHD \time_div_reg[5]  (.Q(time_div[5]),
	.QB(UNCONNECTED6),
	.D(n_122),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_div_reg[3]  (.Q(time_div[3]),
	.QB(UNCONNECTED7),
	.D(n_124),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_div_reg[1]  (.Q(time_div[1]),
	.QB(UNCONNECTED8),
	.D(n_126),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_cnt_reg[1]  (.Q(time_cnt[1]),
	.QB(UNCONNECTED9),
	.D(n_118),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_div_reg[6]  (.Q(time_div[6]),
	.QB(UNCONNECTED10),
	.D(n_127),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_div_reg[4]  (.Q(time_div[4]),
	.QB(UNCONNECTED11),
	.D(n_123),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_div_reg[7]  (.Q(time_div[7]),
	.QB(UNCONNECTED12),
	.D(n_116),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_div_reg[2]  (.Q(time_div[2]),
	.QB(UNCONNECTED13),
	.D(n_121),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_cnt_reg[5]  (.Q(time_cnt[5]),
	.QB(UNCONNECTED14),
	.D(n_115),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_cnt_reg[4]  (.Q(time_cnt[4]),
	.QB(UNCONNECTED15),
	.D(n_114),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_cnt_reg[3]  (.Q(time_cnt[3]),
	.QB(UNCONNECTED16),
	.D(n_120),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_div_reg[0]  (.Q(time_div[0]),
	.QB(UNCONNECTED17),
	.D(n_125),
	.CKB(clk),
	.RB(n_148));
   DBFRBEHD \time_cnt_reg[2]  (.Q(time_cnt[2]),
	.QB(UNCONNECTED18),
	.D(n_117),
	.CKB(clk),
	.RB(n_148));
   XOR2EHD g7051__8428 (.O(n_135),
	.I1(tmax[6]),
	.I2(n_128));
   ND2CHD g7056__5526 (.O(n_134),
	.I1(n_132),
	.I2(ibat[7]));
   NR2BHD g7057__6783 (.O(n_133),
	.I1(ibat[7]),
	.I2(n_132));
   OAI22CHD g7024__3680 (.O(n_131),
	.A1(time_cnt[0]),
	.A2(n_129),
	.B1(n_144),
	.B2(n_5));
   MOAI1CHD g7030__1617 (.O(n_130),
	.A1(n_129),
	.A2(n_128),
	.B1(n_129),
	.B2(time_cnt[6]));
   OA112EHD g7040__2802 (.O(n_127),
	.A1(logic_1_1_net),
	.B1(n_101),
	.C1(n_96),
	.C2(time_div[6]));
   OA112EHD g7034__1705 (.O(n_126),
	.A1(logic_1_1_net),
	.B1(n_23),
	.C1(time_div[1]),
	.C2(time_div[0]));
   OA112EHD g7036__5122 (.O(n_124),
	.A1(logic_1_1_net),
	.B1(n_69),
	.C1(n_64),
	.C2(time_div[3]));
   OA112EHD g7037__8246 (.O(n_123),
	.A1(logic_1_1_net),
	.B1(n_95),
	.C1(n_72),
	.C2(time_div[4]));
   OA112EHD g7033__7098 (.O(n_121),
	.A1(logic_1_1_net),
	.B1(n_52),
	.C1(n_40),
	.C2(time_div[2]));
   MOAI1CHD g7027__6131 (.O(n_120),
	.A1(n_129),
	.A2(n_84),
	.B1(n_129),
	.B2(time_cnt[3]));
   INVDHD g7050 (.O(n_119),
	.I(n_137));
   MOAI1CHD g7025__1881 (.O(n_118),
	.A1(n_129),
	.A2(n_83),
	.B1(n_129),
	.B2(time_cnt[1]));
   MOAI1CHD g7026__5115 (.O(n_117),
	.A1(n_129),
	.A2(n_136),
	.B1(n_129),
	.B2(time_cnt[2]));
   MOAI1CHD g7029__4733 (.O(n_115),
	.A1(n_129),
	.A2(n_109),
	.B1(n_129),
	.B2(time_cnt[5]));
   MOAI1CHD g7028__6161 (.O(n_114),
	.A1(n_129),
	.A2(n_99),
	.B1(n_129),
	.B2(time_cnt[4]));
   MAO222CHD g7071__9315 (.O(n_139),
	.A1(n_107),
	.B1(n_7),
	.C1(tbat[6]));
   MAO222CHD g7054__9945 (.O(n_113),
	.A1(n_104),
	.B1(n_1),
	.C1(tempmax[6]));
   MAOI1CHD g7052__2883 (.O(n_137),
	.A1(n_112),
	.A2(time_cnt[7]),
	.B1(time_cnt[7]),
	.B2(n_112));
   MAO222CHD g7077__2346 (.O(n_111),
	.A1(n_106),
	.B1(vbat[4]),
	.C1(n_44));
   MAO222CHD g7061__1666 (.O(n_132),
	.A1(n_102),
	.B1(ibat[6]),
	.C1(n_6));
   INVDHD g7045 (.O(n_144),
	.I(n_129));
   XOR2EHD g7060__7410 (.O(n_110),
	.I1(tmax[5]),
	.I2(n_109));
   OAI12CHD g7059__6417 (.O(n_128),
	.A1(n_112),
	.B1(n_105),
	.B2(time_cnt[6]));
   ND2CHD g7053__5477 (.O(n_129),
	.I1(n_108),
	.I2(time_div[7]));
   OAI22CHD g7078__2398 (.O(n_107),
	.A1(tempmin[5]),
	.A2(n_94),
	.B1(n_93),
	.B2(n_103));
   MAO222CHD g7088__5107 (.O(n_106),
	.A1(n_89),
	.B1(vbat[3]),
	.C1(n_56));
   ND2CHD g7063__6260 (.O(n_112),
	.I1(n_105),
	.I2(time_cnt[6]));
   MAO222CHD g7065__4319 (.O(n_104),
	.A1(n_88),
	.B1(n_103),
	.C1(tempmax[5]));
   MAO222CHD g7072__8428 (.O(n_102),
	.A1(n_87),
	.B1(n_3),
	.C1(ibat[5]));
   INVDHD g7055 (.O(n_108),
	.I(n_101));
   OAI12CHD g7069__5526 (.O(n_109),
	.A1(n_92),
	.B1(n_86),
	.B2(time_cnt[5]));
   MAOI1CHD g7070__6783 (.O(n_100),
	.A1(n_99),
	.A2(tmax[4]),
	.B1(tmax[4]),
	.B2(n_99));
   OA13CHD g7087__3680 (.O(n_98),
	.A1(n_91),
	.B1(n_90),
	.B2(n_75),
	.B3(vpreset[4]));
   AO12EHD g7068__1617 (.O(n_97),
	.A1(n_96),
	.B1(n_95),
	.B2(n_80));
   ND2DHD g7062__2802 (.O(n_101),
	.I1(n_96),
	.I2(time_div[6]));
   AN2CHD g7084__1705 (.O(n_94),
	.I1(n_93),
	.I2(n_103));
   INVDHD g7074 (.O(n_105),
	.I(n_92));
   OA222CHD g7092__5122 (.O(n_91),
	.A1(n_51),
	.A2(n_62),
	.B1(n_76),
	.B2(n_90),
	.C1(vpreset[7]),
	.C2(n_22));
   MAO222CHD g7095__8246 (.O(n_89),
	.A1(n_74),
	.B1(vbat[2]),
	.C1(n_58));
   MAO222CHD g7075__7098 (.O(n_88),
	.A1(n_78),
	.B1(n_82),
	.C1(tempmax[4]));
   MAO222CHD g7082__6131 (.O(n_87),
	.A1(n_77),
	.B1(n_11),
	.C1(ibat[4]));
   ND2CHD g7076__1881 (.O(n_92),
	.I1(n_86),
	.I2(time_cnt[5]));
   AOI22BHD g7081__5115 (.O(n_85),
	.A1(n_84),
	.A2(tmax[3]),
	.B1(n_83),
	.B2(tmax[1]));
   MAO222CHD g7093__7482 (.O(n_93),
	.A1(n_71),
	.B1(n_82),
	.C1(tempmin[4]));
   OAI22CHD g7079__4733 (.O(n_81),
	.A1(tmax[3]),
	.A2(n_84),
	.B1(n_83),
	.B2(tmax[1]));
   NR2CHD g7073__6161 (.O(n_96),
	.I1(n_80),
	.I2(n_95));
   OAI12CHD g7080__9315 (.O(n_99),
	.A1(n_79),
	.B1(n_73),
	.B2(time_cnt[4]));
   INVDHD g7083 (.O(n_86),
	.I(n_79));
   MAO222CHD g7089__9945 (.O(n_78),
	.A1(n_66),
	.B1(n_70),
	.C1(tempmax[3]));
   MAO222CHD g7091__2883 (.O(n_77),
	.A1(n_63),
	.B1(n_4),
	.C1(ibat[3]));
   AO222CHD g7100__2346 (.O(n_76),
	.A1(n_75),
	.A2(vpreset[4]),
	.B1(n_59),
	.B2(n_30),
	.C1(n_28),
	.C2(vpreset[3]));
   MAO222EHD g7103__1666 (.O(n_74),
	.A1(n_61),
	.B1(vbat[1]),
	.C1(n_48));
   ND2CHD g7085__7410 (.O(n_79),
	.I1(n_73),
	.I2(time_cnt[4]));
   ND2DHD g7086__6417 (.O(n_95),
	.I1(n_72),
	.I2(time_div[4]));
   OAI12CHD g7094__5477 (.O(n_84),
	.A1(n_68),
	.B1(n_65),
	.B2(time_cnt[3]));
   OA112CHD g7099__2398 (.O(n_71),
	.A1(n_60),
	.B1(n_54),
	.C1(n_70),
	.C2(tempmin[3]));
   INVDHD g7090 (.O(n_72),
	.I(n_69));
   INVDHD g7096 (.O(n_73),
	.I(n_68));
   ND3CHD g7104__5107 (.O(n_168),
	.I1(n_153),
	.I2(n_67),
	.I3(vtok));
   MAO222CHD g7101__6260 (.O(n_66),
	.A1(n_39),
	.B1(n_26),
	.C1(tempmax[2]));
   ND2CHD g7098__4319 (.O(n_68),
	.I1(n_65),
	.I2(time_cnt[3]));
   ND2DHD g7097__8428 (.O(n_69),
	.I1(n_64),
	.I2(time_div[3]));
   MAO222CHD g7105__5526 (.O(n_63),
	.A1(n_42),
	.B1(n_13),
	.C1(ibat[2]));
   AOI22BHD g7110__6783 (.O(n_62),
	.A1(n_38),
	.A2(vbat[5]),
	.B1(n_19),
	.B2(vbat[6]));
   OR2EHD g7109__3680 (.O(n_61),
	.I1(vbat[0]),
	.I2(n_47));
   OAI112BHD g7106__1617 (.O(n_60),
	.A1(n_27),
	.B1(n_53),
	.C1(n_32),
	.C2(tbat[0]));
   OAI222BHD g7114__2802 (.O(n_59),
	.A1(vbat[1]),
	.A2(n_9),
	.B1(n_35),
	.B2(vbat[0]),
	.C1(vbat[2]),
	.C2(n_29));
   OAI12CHD g7107__1705 (.O(n_136),
	.A1(n_50),
	.B1(n_41),
	.B2(time_cnt[2]));
   OAI22CHD g7121__5122 (.O(n_58),
	.A1(vpreset[2]),
	.A2(n_55),
	.B1(n_57),
	.B2(vcutoff[2]));
   OAI22CHD g7120__8246 (.O(n_56),
	.A1(vpreset[3]),
	.A2(n_55),
	.B1(n_57),
	.B2(vcutoff[3]));
   OR3B2CHD g7118__7098 (.O(n_54),
	.I1(tempmin[2]),
	.B1(n_53),
	.B2(tbat[2]));
   INVDHD g7102 (.O(n_64),
	.I(n_52));
   OAI112BHD g7116__6131 (.O(n_67),
	.A1(vbat[6]),
	.B1(vbat[7]),
	.C1(n_21),
	.C2(vbat[5]));
   AO112EHD g7119__1881 (.O(n_90),
	.A1(n_51),
	.B1(n_37),
	.C1(n_0),
	.C2(vpreset[5]));
   INVDHD g7108 (.O(n_65),
	.I(n_50));
   OAI22CHD g7126__5115 (.O(n_49),
	.A1(vpreset[7]),
	.A2(n_55),
	.B1(n_57),
	.B2(vcutoff[7]));
   OAI22CHD g7129__7482 (.O(n_48),
	.A1(vpreset[1]),
	.A2(n_55),
	.B1(n_57),
	.B2(vcutoff[1]));
   OAI22CHD g7124__4733 (.O(n_47),
	.A1(vpreset[0]),
	.A2(n_55),
	.B1(n_57),
	.B2(vcutoff[0]));
   OAI22CHD g7125__6161 (.O(n_46),
	.A1(vpreset[5]),
	.A2(n_55),
	.B1(n_57),
	.B2(vcutoff[5]));
   AOI22BHD g7128__9315 (.O(n_45),
	.A1(n_57),
	.A2(vpreset[6]),
	.B1(n_55),
	.B2(vcutoff[6]));
   AOI22BHD g7127__9945 (.O(n_44),
	.A1(n_57),
	.A2(vpreset[4]),
	.B1(n_55),
	.B2(vcutoff[4]));
   NR2CHD g7122__2883 (.O(n_169),
	.I1(n_43),
	.I2(n_153));
   AN2CHD g7123__2346 (.O(n_148),
	.I1(cv),
	.I2(n_178));
   MAO222CHD g7113__1666 (.O(n_42),
	.A1(n_15),
	.B1(n_8),
	.C1(ibat[1]));
   ND2CHD g7112__7410 (.O(n_50),
	.I1(n_41),
	.I2(time_cnt[2]));
   ND2DHD g7111__6417 (.O(n_52),
	.I1(n_40),
	.I2(time_div[2]));
   MAO222CHD g7115__5477 (.O(n_39),
	.A1(n_16),
	.B1(n_31),
	.C1(tempmax[1]));
   NR2BHD g7130__2398 (.O(n_38),
	.I1(vpreset[5]),
	.I2(n_37));
   ND2CHD g7134__5107 (.O(FE_OFN14_tmonen),
	.I1(n_161),
	.I2(state[1]));
   OAI12CHD g7131__6260 (.O(n_35),
	.A1(vpreset[0]),
	.B1(n_10),
	.B2(vpreset[1]));
   NR2BHD g7133__4319 (.O(FE_OFN10_cc),
	.I1(state[2]),
	.I2(n_55));
   OR2B1CHD g7137__8428 (.O(FE_OFN13_vmonen),
	.I1(n_24),
	.B1(state[2]));
   OAI12CHD g7136__5526 (.O(n_32),
	.A1(tempmin[0]),
	.B1(n_31),
	.B2(tempmin[1]));
   ND2CHD g7135__6783 (.O(n_43),
	.I1(n_17),
	.I2(vtok));
   MAOI1CHD g7139__3680 (.O(n_30),
	.A1(n_29),
	.A2(vbat[2]),
	.B1(vpreset[3]),
	.B2(n_28));
   AOI22BHD g7138__1617 (.O(n_27),
	.A1(n_31),
	.A2(tempmin[1]),
	.B1(n_26),
	.B2(tempmin[2]));
   AN2KHD g7132__2802 (.O(tc),
	.I1(n_24),
	.I2(state[2]));
   OAI12CHD g7141__1705 (.O(n_83),
	.A1(n_20),
	.B1(time_cnt[1]),
	.B2(time_cnt[0]));
   NR3BHD g7140__5122 (.O(FE_OFN11_cv),
	.I1(state[1]),
	.I2(n_2),
	.I3(n_18));
   ND2CHD g7146__8246 (.O(n_53),
	.I1(n_70),
	.I2(tempmin[3]));
   INVDHD g7117 (.O(n_40),
	.I(n_23));
   AN2CHD g7143__7098 (.O(n_51),
	.I1(n_22),
	.I2(vpreset[7]));
   INVDHD g7150 (.O(n_57),
	.I(n_55));
   NR2BHD g7153__6131 (.O(n_21),
	.I1(n_75),
	.I2(n_28));
   INVDHD g7149 (.O(n_41),
	.I(n_20));
   NR2BHD g7147__1881 (.O(n_37),
	.I1(vbat[6]),
	.I2(n_19));
   ND2DHD g7148__5115 (.O(n_161),
	.I1(n_18),
	.I2(state[0]));
   ND2DHD g7151__7482 (.O(n_17),
	.I1(state[2]),
	.I2(state[1]));
   OR2B1CHD g7145__4733 (.O(n_16),
	.I1(tempmax[0]),
	.B1(tbat[0]));
   OR2B1CHD g7144__6161 (.O(n_15),
	.I1(ibat[0]),
	.B1(iend[0]));
   AN2CHD g7157__9315 (.O(n_178),
	.I1(en),
	.I2(rstz));
   ND2DHD g7158__9945 (.O(n_55),
	.I1(state[1]),
	.I2(state[0]));
   NR2BHD g7152__2883 (.O(n_14),
	.I1(tmax[0]),
	.I2(time_cnt[0]));
   NR2BHD g7142__2346 (.O(n_24),
	.I1(state[1]),
	.I2(state[0]));
   ND2CHD g7154__1666 (.O(n_20),
	.I1(time_cnt[1]),
	.I2(time_cnt[0]));
   ND2DHD g7155__7410 (.O(n_23),
	.I1(time_div[1]),
	.I2(time_div[0]));
   NR2CHD g7156__6417 (.O(n_153),
	.I1(state[1]),
	.I2(state[2]));
   INVCKDHD g7163 (.O(n_13),
	.I(iend[2]));
   INVCKDHD g7180 (.O(n_12),
	.I(tbat[7]));
   INVCKDHD g7164 (.O(n_11),
	.I(iend[4]));
   INVCKDHD g7182 (.O(n_10),
	.I(vbat[1]));
   INVCKDHD g7178 (.O(n_9),
	.I(vpreset[1]));
   INVCKDHD g7159 (.O(n_8),
	.I(iend[1]));
   INVCKDHD g7176 (.O(n_7),
	.I(tempmin[6]));
   INVCKDHD g7179 (.O(n_19),
	.I(vpreset[6]));
   INVDHD g7174 (.O(n_18),
	.I(state[2]));
   INVCKDHD g7181 (.O(n_82),
	.I(tbat[4]));
   INVCKDHD g7170 (.O(n_22),
	.I(vbat[7]));
   INVCKDHD g7166 (.O(n_70),
	.I(tbat[3]));
   INVCKDHD g7171 (.O(n_28),
	.I(vbat[3]));
   INVCKDHD g7160 (.O(n_6),
	.I(iend[6]));
   INVDHD g7173 (.O(n_5),
	.I(time_cnt[0]));
   INVCKDHD g7162 (.O(n_4),
	.I(iend[3]));
   INVCKDHD g7161 (.O(n_3),
	.I(iend[5]));
   INVCKDHD g7184 (.O(n_2),
	.I(state[0]));
   INVCKDHD g7167 (.O(n_1),
	.I(tbat[6]));
   INVCKDHD g7183 (.O(n_0),
	.I(vbat[5]));
   INVCKDHD g7175 (.O(n_80),
	.I(time_div[5]));
   INVCKDHD g7177 (.O(n_29),
	.I(vpreset[2]));
   INVCKDHD g7165 (.O(n_26),
	.I(tbat[2]));
   INVCKDHD g7168 (.O(n_103),
	.I(tbat[5]));
   INVCKDHD g7169 (.O(n_31),
	.I(tbat[1]));
   INVCKDHD g7172 (.O(n_75),
	.I(vbat[4]));
   INVCKDHD g7205 (.O(n_125),
	.I(time_div[0]));
   INVCKDHD g7206 (.O(n_122),
	.I(n_97));
   TIE1DHD tie_1_cell (.O(logic_1_1_net));
endmodule

